DROP VIEW IF EXISTS V_GERENCIA_COODENADAS;

CREATE VIEW V_GERENCIA_COODENADAS AS
SELECT
    VICE,
    GEO_LATITUDE,
    GEO_LONGITUDE
FROM (
    SELECT
        VICE,
        GEO_LATITUDE,
        GEO_LONGITUDE,
        ROW_NUMBER() OVER (
            PARTITION BY VICE
            ORDER BY VICE
        ) AS rn
    FROM MAP_DATA_MAP_CAMPO
    WHERE GEO_LATITUDE IS NOT NULL
      AND GEO_LONGITUDE IS NOT NULL
)
WHERE rn = 1;
