DROP VIEW IF EXISTS MAP_DATA_MAP_VARIACION;

CREATE VIEW MAP_DATA_MAP_VARIACION AS
WITH gerencias AS (
    SELECT DISTINCT GERENCIA FROM V_CRUDO_VARIACION_GER
    UNION
    SELECT DISTINCT GERENCIA FROM V_CRUDO_VARIACION_GER_PROGRAMADO
    UNION
    SELECT DISTINCT GERENCIA FROM V_PRODUCCION_POP
    UNION
    SELECT DISTINCT GERENCIA FROM V_GERENCIA_COODENADAS
)
SELECT
    g.GERENCIA,
    crudo.VAR_PCT AS VAR_PCT_MES,
    prog.VAR_PCT AS VAR_PCT_PROG,
    pop.VARIACION_PORCT AS VAR_PCT_POP,
    coords.GEO_LATITUDE,
    coords.GEO_LONGITUDE
FROM gerencias AS g
LEFT JOIN V_CRUDO_VARIACION_GER AS crudo
    ON crudo.GERENCIA = g.GERENCIA
LEFT JOIN V_CRUDO_VARIACION_GER_PROGRAMADO AS prog
    ON prog.GERENCIA = g.GERENCIA
LEFT JOIN V_PRODUCCION_POP AS pop
    ON pop.GERENCIA = g.GERENCIA
LEFT JOIN V_GERENCIA_COODENADAS AS coords
    ON coords.GERENCIA = g.GERENCIA
ORDER BY g.GERENCIA;
